### ISSUE TITLE
招商银行又重新寄EML账单了，可是

### ISSUE THREAD

**Issue by heyeshuang** [heyeshuang/beancount-homemade-importers#2]
之前用于定位的class和图片地址都出现了变化，`cmb_eml`脚本暂时还用不了

需要观察一段时间看看classname到底是怎么回事。

**Comment by Doslin** [comment]
招商银行又重新寄EML账单了
----------------------------
这个你怎么配置的，没有找到呢

**Comment by heyeshuang** [comment]
我之前是在`掌上生活`APP，搜索`账单服务`找到的

**Comment by heyeshuang** [comment]
似乎是好了，我也不知道我干啥了
